### ISSUE TITLE
issue loading report

### ISSUE THREAD

**Issue by ngner** [christopherlam/bas-report#1]
I have tried adding this to GNU Cash 2.6.15 
but get the following
```
;;; note: auto-compilation is enabled, set GUILE_AUTO_COMPILE=0
;;;       or pass the --no-auto-compile argument to disable.
;;; compiling /usr/share/gnucash/scm/gnucash/report/standard-reports/business-tax-report.scm
;;; WARNING: compilation of /usr/share/gnucash/scm/gnucash/report/standard-reports/business-tax-report.scm failed:
;;; ERROR: In procedure scm_i_lreadparen: gnucash/report/standard-reports/business-tax-report.scm:7524:1: end of file
Backtrace:
In ice-9/boot-9.scm:
3589: 19 [process-use-modules (((gnucash report standard-reports)))]
 705: 18 [map #<procedure 55c0036edd40 at ice-9/boot-9.scm:3589:25 (mif-args)> ((#))]
3590: 17 [#<procedure 55c0036edd40 at ice-9/boot-9.scm:3589:25 (mif-args)> (#)]
2867: 16 [resolve-interface (gnucash report standard-reports) #:select ...]
2792: 15 [#<procedure 55c0036e0620 at ice-9/boot-9.scm:2780:4 (name #:optional autoload version #:key ensure)> # ...]
3068: 14 [try-module-autoload (gnucash report standard-reports) #f]
2404: 13 [save-module-excursion #<procedure 55c0042dca80 at ice-9/boot-9.scm:3069:17 ()>]
3088: 12 [#<procedure 55c0042dca80 at ice-9/boot-9.scm:3069:17 ()>]
In unknown file:
   ?: 11 [primitive-load-path "gnucash/report/standard-reports" ...]
In standard-reports.scm:
 149: 10 [#<procedure 55c0045606e0 ()>]
In ice-9/boot-9.scm:
 771: 9 [for-each #<procedure 55c00462b2a0 at standard-reports.scm:150:4 (x)> #]
In standard-reports.scm:
 153: 8 [#<procedure 55c00462b2a0 at standard-reports.scm:150:4 (x)> business-tax-report]
In ice-9/boot-9.scm:
2867: 7 [resolve-interface (gnucash report standard-reports ...) #:select ...]
2792: 6 [#<procedure 55c0036e0620 at ice-9/boot-9.scm:2780:4 (name #:optional autoload version #:key ensure)> # ...]
3068: 5 [try-module-autoload (gnucash report standard-reports ...) #f]
2404: 4 [save-module-excursion #<procedure 55c003e1c870 at ice-9/boot-9.scm:3069:17 ()>]
3088: 3 [#<procedure 55c003e1c870 at ice-9/boot-9.scm:3069:17 ()>]
In unknown file:
   ?: 2 [primitive-load-path "gnucash/report/standard-reports/business-tax-report" ...]
In ice-9/eval.scm:
 393: 1 [eval #<memoized <!DOCTYPE> ()]
In unknown file:
   ?: 0 [memoize-variable-access! #<memoized <!DOCTYPE> #<module # 55c003581ab0>]

ERROR: In procedure memoize-variable-access!:
ERROR: Unbound variable: <!DOCTYPE
```

**Comment by ngner** [comment]
removed the files from standard-reports and tested again from ~/.gnucash 
Now receive the following:
'''
gnucash --debug --log gnc.scm=debug
;;; note: source file /usr/share/gnucash/scm/gnucash/report/invoice.scm
;;;       newer than compiled /usr/lib/x86_64-linux-gnu/gnucash/gnucash/scm/ccache/2.0/gnucash/report/invoice.go
;;; found fresh local cache at /home/nick/.cache/guile/ccache/2.0-LE-8-2.0/usr/share/gnucash/scm/gnucash/report/invoice.scm.go
;;; note: auto-compilation is enabled, set GUILE_AUTO_COMPILE=0
;;;       or pass the --no-auto-compile argument to disable.
;;; compiling /home/nick/.gnucash/report-other-menu.scm
;;; WARNING: compilation of /home/nick/.gnucash/report-other-menu.scm failed:
;;; ERROR: Syntax error:
;;; /home/nick/.gnucash/report-other-menu.scm:564:69: define-module: expected keyword arg in subform </td> of (define-module (gnucash report-other-menu) </td> </tr> <tr> <td id= "L32" class= "blob-num js-line-number" data-line-number= "32" ></td> <td id= "LC32" class= "blob-code blob-code-inner js-file-line" > #:export (gnc:menuname-other))
Found Finance::Quote version 1.38
'''

**Comment by ngner** [comment]
My stupidity is the cause - I had incorrectly downloaded the 
report-other-menu.scm

All now working !!  Many thanks

**Comment by christopherlam** [comment]
https://github.com/christopherlam/gnucash/blob/unstable-report-amendments/gnucash/report/standard-reports/income-gst-statement.scm

**Comment by christopherlam** [comment]
Well the bas-report has now been renamed to income-gst-statement and will be part of standard-reports as from 2.7 onwards.

I'm still hacking on it.

https://github.com/christopherlam/gnucash/blob/unstable-report-amendments/gnucash/report/standard-reports/income-gst-statement.scm
